### ISSUE TITLE
Don't change `self.allowed_ips` in `GatewayClientPeerAdapter.trusted_ips` method

### ISSUE THREAD

**Issue by facundobatista** [openstack-charmers/charm-ceph-iscsi#10]
It's a bad idiom to change structures on a "read property".

Consider what would happen if you do `print(adapter.trusted_ips)` several times, it will be different on each `print` call.

**Comment by gnuoy** [comment]
`self.allowed_ips` is a class property itself and does not get mutated by `trusted_ips`, calling `print(adapter.trusted_ips)` will not result in different results. Having said that I think it could easily break in the way you've described in the future if the structure of `self.allowed_ips` is changed.

**Comment by gnuoy** [comment]
https://review.opendev.org/#/c/749467
