### ISSUE TITLE
Let the logging module to build the messages

### ISSUE THREAD

**Issue by facundobatista** [openstack-charmers/charm-ceph-iscsi#11]
Example, in `CephISCSIGatewayCharmBase`, convert...

```
        logging.info("Using {} class".format(self.release))
```

...to...

```
        logging.info("Using %s class", self.release)
```

This is for performance and robustness.

For performance because if the logger decides that the message will not be sent, the string is not built at all. 

For robustness because in the event of introducing a bug in the line, the logging infrastructure will not crash, but report the problem. For example, in this case: `logger.info("Foo %s: %d", self.quantity)`.

**Comment by gnuoy** [comment]
https://review.opendev.org/#/c/749648/
https://review.opendev.org/#/c/749647/
https://review.opendev.org/#/c/749646/
