### ISSUE TITLE
Please ensure the components you use have issue trackers set up

### ISSUE THREAD

**Issue by chipaca** [openstack-charmers/charm-ceph-iscsi#13]
There are a bunch of issues I'd like to file on the _components_ you're using, that I can't.

**Comment by gnuoy** [comment]
Projects created on launchpad for the components and bug tracking of the charm itself has moved to launchpad

https://launchpad.net/charm-ops-interface-tls-certificates
https://launchpad.net/charm-ops-interface-ceph-client
https://launchpad.net/charm-ops-openstack
https://launchpad.net/charm-ceph-iscsi
